package cliconfig

// SupportedTools mengembalikan daftar seluruh perkakas AI CLI yang didukung Route-X.
// Seluruh perkakas secara default mengarah ke model kanonik riil yang terdaftar di katalog sistem.
func SupportedTools() []ToolDef {
	return []ToolDef{
		{
			ID:            "agy",
			Name:          "Antigravity CLI",
			Category:      "Coding Agent",
			Description:   "Google DeepMind Advanced Agentic Coding CLI untuk eksekusi tugas otonom dan pair-programming.",
			BinaryNames:   []string{"agy", "antigravity"},
			ConfigPaths:   []string{".gemini/antigravity-cli/config.json", ".config/agy/config.json"},
			VersionArg:    "--version",
			EnvVarBaseURL: "OPENAI_API_BASE",
			EnvVarAPIKey:  "OPENAI_API_KEY",
			EnvVarModel:   "ANTIGRAVITY_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "claude",
			Name:          "Claude Code",
			Category:      "Coding Agent",
			Description:   "Anthropic Claude Code CLI untuk analisis basis kode, refactoring, dan penyuntingan berkas.",
			BinaryNames:   []string{"claude", "claude-code"},
			ConfigPaths:   []string{".claude/settings.json", ".claude.json"},
			VersionArg:    "--version",
			EnvVarBaseURL: "ANTHROPIC_BASE_URL",
			EnvVarAPIKey:  "ANTHROPIC_API_KEY",
			EnvVarModel:   "ANTHROPIC_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "claude-sonnet-5",
		},
		{
			ID:            "opencode",
			Name:          "OpenCode CLI",
			Category:      "Coding Agent",
			Description:   "Terminal coding assistant opensource dengan dukungan multi-provider model AI.",
			BinaryNames:   []string{"opencode", "opencode-cli"},
			ConfigPaths:   []string{".config/opencode/config.json"},
			VersionArg:    "--version",
			EnvVarBaseURL: "OPENCODE_API_BASE",
			EnvVarAPIKey:  "OPENCODE_API_KEY",
			EnvVarModel:   "OPENCODE_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "aider",
			Name:          "Aider",
			Category:      "Coding Agent",
			Description:   "AI pair programming tool di terminal yang langsung menyunting dan commit kode ke git.",
			BinaryNames:   []string{"aider"},
			ConfigPaths:   []string{".aider.conf.yml"},
			VersionArg:    "--version",
			EnvVarBaseURL: "OPENAI_API_BASE",
			EnvVarAPIKey:  "OPENAI_API_KEY",
			EnvVarModel:   "AIDER_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "ollama",
			Name:          "Ollama CLI",
			Category:      "Local LLM",
			Description:   "CLI runner model open-source lokal (Llama, DeepSeek, Qwen, Mistral).",
			BinaryNames:   []string{"ollama"},
			ConfigPaths:   []string{".ollama"},
			VersionArg:    "--version",
			EnvVarBaseURL: "OLLAMA_HOST",
			EnvVarAPIKey:  "OLLAMA_API_KEY",
			EnvVarModel:   "OLLAMA_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "sgpt",
			Name:          "Shell GPT",
			Category:      "Terminal Assistant",
			Description:   "Perkakas CLI bertenaga AI untuk generasi perintah shell, analisis log, dan obrolan terminal.",
			BinaryNames:   []string{"sgpt"},
			ConfigPaths:   []string{".config/shell_gpt/.sgptrc"},
			VersionArg:    "--version",
			EnvVarBaseURL: "OPENAI_BASE_URL",
			EnvVarAPIKey:  "OPENAI_API_KEY",
			EnvVarModel:   "DEFAULT_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "fabric",
			Name:          "Fabric AI",
			Category:      "Workflow & Prompts",
			Description:   "Framework modular untuk mengotomatiskan prompting cerdas dan ekstraksi pola via terminal.",
			BinaryNames:   []string{"fabric"},
			ConfigPaths:   []string{".config/fabric/.env"},
			VersionArg:    "--version",
			EnvVarBaseURL: "OPENAI_BASE_URL",
			EnvVarAPIKey:  "OPENAI_API_KEY",
			EnvVarModel:   "DEFAULT_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "continue",
			Name:          "Continue CLI",
			Category:      "Coding Agent",
			Description:   "Ekstensi dan CLI pendamping coding modular open-source untuk IDE dan shell.",
			BinaryNames:   []string{"continue"},
			ConfigPaths:   []string{".continue/config.json", ".continue/config.yaml"},
			VersionArg:    "--version",
			EnvVarBaseURL: "CONTINUE_API_BASE",
			EnvVarAPIKey:  "CONTINUE_API_KEY",
			EnvVarModel:   "CONTINUE_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "llm",
			Name:          "SimonW LLM",
			Category:      "Terminal Assistant",
			Description:   "CLI serbaguna Simon Willison untuk query model LLM, prompt templates, dan embeddings.",
			BinaryNames:   []string{"llm"},
			ConfigPaths:   []string{".config/io.datasette.llm/default_model.txt"},
			VersionArg:    "--version",
			EnvVarBaseURL: "OPENAI_API_BASE",
			EnvVarAPIKey:  "OPENAI_API_KEY",
			EnvVarModel:   "LLM_DEFAULT_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "goose",
			Name:          "Goose Agent",
			Category:      "Developer Agent",
			Description:   "Developer agent open-source dari Block untuk otomatisasi pekerjaan rekayasa perangkat lunak.",
			BinaryNames:   []string{"goose"},
			ConfigPaths:   []string{".config/goose/config.yaml"},
			VersionArg:    "version",
			EnvVarBaseURL: "GOOSE_OPENAI_HOST",
			EnvVarAPIKey:  "GOOSE_API_KEY",
			EnvVarModel:   "GOOSE_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "opencommit",
			Name:          "OpenCommit",
			Category:      "Git Automation",
			Description:   "Generator otomatis pesan commit konvensional git berbasis inferensi diff kode.",
			BinaryNames:   []string{"opencommit", "oco"},
			ConfigPaths:   []string{".opencommit"},
			VersionArg:    "--version",
			EnvVarBaseURL: "OCO_OPENAI_BASE_PATH",
			EnvVarAPIKey:  "OCO_OPENAI_API_KEY",
			EnvVarModel:   "OCO_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "mentat",
			Name:          "Mentat",
			Category:      "Coding Agent",
			Description:   "AI coding partner yang dapat mengoordinasikan pengeditan banyak berkas sekaligus.",
			BinaryNames:   []string{"mentat"},
			ConfigPaths:   []string{".mentat/config.json"},
			VersionArg:    "--version",
			EnvVarBaseURL: "OPENAI_API_BASE",
			EnvVarAPIKey:  "OPENAI_API_KEY",
			EnvVarModel:   "MENTAT_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "plandex",
			Name:          "Plandex",
			Category:      "Terminal Engine",
			Description:   "Terminal AI coding engine untuk tugas rekayasa berukuran besar dan multi-tahap.",
			BinaryNames:   []string{"plandex"},
			ConfigPaths:   []string{".plandex/config.json"},
			VersionArg:    "version",
			EnvVarBaseURL: "PLANDEX_OPENAI_API_HOST",
			EnvVarAPIKey:  "PLANDEX_OPENAI_API_KEY",
			EnvVarModel:   "PLANDEX_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "chatblade",
			Name:          "Chatblade",
			Category:      "Terminal Assistant",
			Description:   "Perkakas CLI cepat untuk interaksi dengan model bahasa dan ekstraksi output JSON.",
			BinaryNames:   []string{"chatblade"},
			ConfigPaths:   []string{".chatblade.yaml"},
			VersionArg:    "--version",
			EnvVarBaseURL: "OPENAI_API_BASE",
			EnvVarAPIKey:  "OPENAI_API_KEY",
			EnvVarModel:   "CHATBLADE_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "gpt-cli",
			Name:          "GPT-CLI",
			Category:      "Terminal Assistant",
			Description:   "Klien baris perintah interaktif untuk percakapan dan penyelesaian tugas di terminal.",
			BinaryNames:   []string{"gpt-cli", "gpt"},
			ConfigPaths:   []string{".config/gpt-cli/gpt.yml"},
			VersionArg:    "-v",
			EnvVarBaseURL: "OPENAI_API_BASE",
			EnvVarAPIKey:  "OPENAI_API_KEY",
			EnvVarModel:   "GPT_CLI_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "cursor-agent",
			Name:          "Cursor Agent",
			Category:      "Coding Agent",
			Description:   "CLI agent untuk antarmuka pengembang Cursor AI dan otomatisasi remote workflow.",
			BinaryNames:   []string{"cursor-agent", "cursor"},
			ConfigPaths:   []string{".cursor/settings.json"},
			VersionArg:    "--version",
			EnvVarBaseURL: "CURSOR_API_BASE",
			EnvVarAPIKey:  "CURSOR_API_KEY",
			EnvVarModel:   "CURSOR_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "copilot",
			Name:          "GitHub Copilot CLI",
			Category:      "Terminal Assistant",
			Description:   "Asisten CLI resmi GitHub untuk penjelasan perintah shell dan git command helper.",
			BinaryNames:   []string{"github-copilot-cli", "copilot"},
			ConfigPaths:   []string{".config/github-copilot/hosts.json"},
			VersionArg:    "--version",
			EnvVarBaseURL: "GITHUB_COPILOT_API_BASE",
			EnvVarAPIKey:  "GITHUB_COPILOT_API_KEY",
			EnvVarModel:   "COPILOT_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "cody",
			Name:          "Sourcegraph Cody",
			Category:      "Coding Agent",
			Description:   "CLI asisten kode cerdas Sourcegraph dengan pemahaman konteks grafik kode menyeluruh.",
			BinaryNames:   []string{"cody"},
			ConfigPaths:   []string{".config/cody/config.json"},
			VersionArg:    "--version",
			EnvVarBaseURL: "SRC_ENDPOINT",
			EnvVarAPIKey:  "SRC_ACCESS_TOKEN",
			EnvVarModel:   "CODY_DEFAULT_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "claude-sonnet-5",
		},
		{
			ID:            "k8sgpt",
			Name:          "K8sGPT",
			Category:      "DevOps & SRE",
			Description:   "Pemindai cluster Kubernetes berbasis AI untuk diagnosis otomatis insiden & error log.",
			BinaryNames:   []string{"k8sgpt"},
			ConfigPaths:   []string{".k8sgpt.yaml"},
			VersionArg:    "version",
			EnvVarBaseURL: "K8SGPT_OPENAI_BASE_URL",
			EnvVarAPIKey:  "K8SGPT_OPENAI_API_KEY",
			EnvVarModel:   "K8SGPT_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
		{
			ID:            "codecompanion",
			Name:          "CodeCompanion CLI",
			Category:      "Coding Agent",
			Description:   "CLI adapter untuk ekosistem AI editor pengembang yang mendukung format OpenAI & Anthropic.",
			BinaryNames:   []string{"codecompanion", "companion"},
			ConfigPaths:   []string{".config/codecompanion/config.json"},
			VersionArg:    "--version",
			EnvVarBaseURL: "CODECOMPANION_API_BASE",
			EnvVarAPIKey:  "CODECOMPANION_API_KEY",
			EnvVarModel:   "CODECOMPANION_MODEL",
			DefaultMode:   ModeModelOnly,
			DefaultTarget: "gpt-5",
		},
	}
}
